kind: Secret
apiVersion: v1
metadata:
  name: keycloak-admin
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
spec:
  secretName: keycloak-tls-secret
  commonName: keycloak-service
  dnsNames:
    - keycloak-service.keycloak.svc.cluster.local
    - keycloak-service.keycloak.svc
    - keycloak-service.keycloak
    - keycloak-service
  issuerRef:
    name: ca-issuer  # Use CA issuer
    kind: Issuer
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  bootstrapAdmin:
    user:
      secret: keycloak-admin
  db:
    host: postgres
    database: keycloak
    passwordSecret:
      key: password
      name: keycloak-db-secret
    usernameSecret:
      key: username
      name: keycloak-db-secret
    vendor: postgres
  ingress:
    enabled: false
  instances: 1
  http:
    tlsSecret: keycloak-tls-secret
  hostname:
    strict: false
