# Test suite configuration file
---
# Flink default version for flink deployment
FLINK_VERSION: "v1_20"

# Image of flink sql runner
SQL_RUNNER_IMAGE: quay.io/streamshub/flink-sql-runner:main

# Operator bundle image of flink operator (leave empty if this install type is not used)
FLINK_OPERATOR_BUNDLE_IMAGE: ""

# Operator bundle image of strimzi operator (leave empty if this install type is not used)
STRIMZI_OPERATOR_BUNDLE_IMAGE: ""

# Use latest released downstream version of strimzi (amq-streams) from catalog
INSTALL_STRIMZI_FROM_RH_CATALOG: "false"

# Use latest released downstream version of apicurio (service-registry) from catalog
INSTALL_APICURIO_FROM_RH_CATALOG: "false"

# Use latest released downstream version of cert-manager from catalog
INSTALL_CERT_MANAGER_FROM_RH_CATALOG: "false"
