apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: streams-e2e-tests-run
  annotations:
    description: "Example PipelineRun for streams e2e tests"
spec:
  pipelineRef:
    name: streams-e2e-tests
  params:
    - name: test-image
      value: "quay.io/streamshub/streams-e2e:latest"
    - name: kubeconfig-secret
      value: "kubeconfig-secret"
    - name: test
      value: ""
    - name: groups
      value: "smoke"
  workspaces:
    - name: test-results
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  timeouts:
    pipeline: "60m"